SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE dbo.ListUser
	@UserName NVARCHAR(200)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT Id, UserName, Password, Email FROM Users WHERE UserName = @UserName
END
GO